### ISSUE TITLE
[Feature Request] Call template variables use other node value 

### ISSUE THREAD

**Issue by HairyRabbit** [HearTao/typei18n#17]
```yaml
foo: 42
bar: 
  baz: wooo~
qux: something {{ .foo }} {{ .bar.baz }}
```

rendered:

```ts
i18n.LANG.qux() // "something 42 wooo~"
```
